### ISSUE TITLE
Cropper component not respecting parent's size

### ISSUE THREAD

**Issue by cryo75** [CropperBlazor/Cropper.Blazor#237]
I have a cropper component in a column:

```html
<div class="row">
    <div class="col-sm-12 col-md-9">
        <CropperComponent @ref="cropperRef"
                            Class="img-container"
                            Src="@Model.Path"
                            InputAttributes="@InputAttributes"
                            Options="cropperOptions" />
    </div>
</div>
```

And the CSS class:

```css
﻿.img-container,
.img-preview {
    text-align: center;
    width: 100%;
}

.img-container {
    height: 400px;
}

.img-preview {
    overflow: hidden;
}

.img-container > ::deep img {
    max-width: 100%;
}

.img-preview > ::deep img {
    max-width: 100%;
}

.preview {
    height: 200px;
    width: 150px;
}
```

When setting a large image, the component just expands (width & height) to fit image.

Is it possible to make the component respect its size defined in the css and/or the its parent?
